sudo: required
services:
  - docker

before_install:
  - docker build -t narf92/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true narf92/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-928532919269"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id: $AWS_ACCES_KEY
  secret_access_key: $AWS_SECRET_KEY
